### ISSUE TITLE
Plug doesn't work with Content-Type: application/json

### ISSUE THREAD

**Issue by sashman** [fanduel/jsonrpc2-elixir#8]
When using:

```elixir
forward "/jsonrpc", JSONRPC2.Servers.HTTP.Plug, YourJSONRPC2HandlerModule
```

and sending via curl, a parse error occurs:

```bash
$ curl "localhost:4000/jsonrpc" -H "Content-Type: application/json" -d '{"jsonrpc":"2.0", "method": "hello", "id": 1}' 
{"jsonrpc":"2.0","id":null,"error":{"message":"Parse error","code":-32700}}%   
```

Digging deeper, in [JSONRPC2.Servers.HTTP.Plug](https://github.com/fanduel/jsonrpc2-elixir/blob/master/lib/jsonrpc2/servers/http/plug.ex), `{:ok, req_body, conn} = Plug.Conn.read_body(conn)` sets `req_body` to empty string. When inspecting the `conn`, the incoming body is definitely there and has already been parsed in the `params` field:

```
%Plug.Conn{adapter: {Plug.Adapters.Cowboy.Conn, :...}, assigns: %{},
...
 params: %{"id" => 1, "jsonrpc" => "2.0", "method" => "hello"},
...
```

So when forcing Content-Type to plain text, the plug works as expected:

```
$ curl "localhost:4000/jsonrpc" -H "Content-Type: plain/text" -d '{"jsonrpc":"2.0", "method": "hello", "id": 1}'
{"result":"Hello!","jsonrpc":"2.0","id":1}%  
```

Is this intended and I might have something misconfigured?

**Comment by jnatherley** [comment]
I found this issue also, did you come up with an alternative resolution @sashman  ?

**Comment by sashman** [comment]
@jnatherley so far just what's in the above-mentioned [PR](https://github.com/fanduel/jsonrpc2-elixir/pull/9)

**Comment by ericentin** [comment]
Closing as will be resolved in next release
